---
title: "secretory_phase_score_Biop"
output: html_document
date: '2022-04-04'
---

<!--
#-------------------------------------------------------------------------------
# This script calculates enrichment scores of gene signature characteristic
# of the secretory phase and WOI in the menstrual cycle

# Author: Carlos Simon Foundation (Raul PM @supermegamio, Diego AC @diegoamoros)
# Date: 2022-04-04
#-------------------------------------------------------------------------------
-->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      error = FALSE, comment = NA, cache = FALSE,
                      R.options = list(width = 320), fig.align = "center", 
                      out.width = "95%", out.width = 3160, fig.width = 12, 
                      fig.height = 10)
```

```{r}
library(Seurat)
library(SeuratDisk)
library(ggplot2)
library(UCell)
library(dittoSeq)
library(escape)
library(yaml)
library(this.path)


## Load config.yml file
find_config <- function(names = c("config.yaml", "config.yml")) {
  currrent.path <- dirname(this.path::this.path())
  dirs <- unique(c(currrent.path, dirname(currrent.path)))
  for (d in dirs) {
    for (nm in names) {
      p <- file.path(d, nm)
      if (file.exists(p))
        return(normalizePath(p, winslash = "/", mustWork = TRUE))
    }
  }
  stop("config.yaml|config.yml not found: ",
       paste(dirs, collapse = " o "), call. = FALSE)
}

config <- yaml.load_file(find_config())

# Set folders
input_file <-  config$secretory_phase_score$input_file
output_folder <- config$secretory_phase_score$output_dir
dir.create(output_folder, recursive = TRUE, showWarnings = FALSE)

# Load Input Dataset
sc_AS <- LoadH5Seurat(file = input_file)
   

```

# Gene Signature Secretory Phase calculator

```{r}

# Fix some annotations
sc_AS$Treatment_stage[which(sc_AS$Treatment_stage == "A-Pre")] <- "AS-Pre"
sc_AS$Treatment_stage[which(sc_AS$Treatment_stage == "B-Post")] <- "AS-Post"

cell_types <- sc_AS$cell_type_AS_FINAL_v2
cell_types[which(cell_types == "Myofibroblasts")] <- "PV contractible"
cell_types[which(cell_types == "Epithelium_SLPI")] <- "AS Epithelium"
sc_AS$cell_type_AS_FINAL_v3 <- cell_types

```


```{r}


## Define gene sets
Menstrual_cycle <- c("SCGB1D2","MT1F", "MT1X", "MT1E", "MT1G", "CXCL14","WNT5A")

WOI <- c("CXCL14","MAOA","DPP4","NUPR1","GPX3",
         "PAEP","S100A4","DKK1","CRYAB","FOXO1","IL15")

Menstrual_cycle_WOI <- c("SCGB1D2","MT1F", "MT1X", "MT1E", "MT1G", "CXCL14",
                         "CXCL14","MAOA","DPP4","NUPR1","GPX3","PAEP",
                         "S100A4","DKK1","CRYAB","FOXO1","IL15")

Menstrual_cycle_stromal <- c("SCGB1D2","MT1F", "MT1X", "MT1E", "MT1G",
                             "CXCL14","WNT5A","SFRP1","ZFYVE21","CILP",
                             "SLF2","MATN2","S100A4")

menstrual_list <- list(Menstrual_cycle, 
                       WOI,Menstrual_cycle_WOI,
                       Menstrual_cycle_stromal)

names(menstrual_list) <- c("Menstrual_cycle_Secretory_phase", 
                           "WOI","Menstrual_cycle_WOI",
                           "Menstrual_cycle_stromal_Epithelium")


## Calculation of score using ucell
Menstrual_cycle_score <- AddModuleScore_UCell(
    sc_AS, maxRank = 5000, force.gc = TRUE,
    features = menstrual_list, ncores = 6, chunk.size = 1000)

sc_AS <- Menstrual_cycle_score
rm(Menstrual_cycle_score)
gc(full = TRUE, reset = TRUE)

## Box Plot of Menstrual_cycle_stromal_Epithelium
ssGSEA_ucell_secretory_menstrual <- dittoBoxPlot(
    sc_AS[,which(sc_AS$cell_type_AS_FINAL_v3 == 
                     c("Epithelium","Stromal","AS Epithelium", 
                       "Endothelium","Perivascular"))], 
    "Menstrual_cycle_stromal_Epithelium_UCell", 
    group.by = "Treatment_stage", 
    split.by = "cell_type_AS_FINAL_v3", 
    jitter.size	= 0.1, 
    color.panel = c("#F8766D", "#00BFC4"), 
    boxplot.width = 0.75) + 
    ggtitle("Mentrual cycle: Secretory phase") + 
    ylab("UCell score") + 
    xlab("Treatment stage")

# Save Plot
ggsave(filename = file.path(output_folder,"fig2d_mens.svg"), 
                         plot = ssGSEA_ucell_secretory_menstrual,
                         device = "svg", width = 8, height = 8, dpi = 320)


## Box Plot of Menstrual_cycle_WOI
ssGSEA_ucell_secretory_menstrual <- dittoBoxPlot(
    sc_AS[,which(sc_AS$cell_type_AS_FINAL_v3 == 
                     c("Epithelium","Stromal","AS Epithelium", 
                       "Endothelium","Perivascular"))], 
    "Menstrual_cycle_WOI_UCell", 
    group.by = "Treatment_stage", 
    split.by = "cell_type_AS_FINAL_v3", 
    jitter.size	= 0.1, 
    color.panel = c("#F8766D", "#00BFC4"), 
    boxplot.width = 0.75) + 
    ggtitle("Mentrual cycle: WOI") + 
    ylab("UCell score") + 
    xlab("Treatment stage")

# Save Plot
ggsave(filename = file.path(output_folder,"fig2d_woi.svg"), 
                         plot = ssGSEA_ucell_secretory_menstrual,
                         device = "svg", width = 8, height = 8, dpi = 320)

      

       
# Statistical testing

sc_AS_df <- sc_AS@meta.data
cell_types <- c("Epithelium","AS Epithelium",
                "Stromal","Endothelium","Perivascular")

ucell_results <- lapply(cell_types, function(x){escape::getSignificance(
    enriched = sc_AS_df[which(sc_AS_df$cell_type_AS_FINAL_v3 == x),], 
    group = "Treatment_stage", 
    gene.sets = c("Menstrual_cycle_Secretory_phase_UCell",
                  "WOI_UCell",
                  "Menstrual_cycle_WOI_UCell"), 
    fit = "Wilcoxon") })

names(ucell_results) <- cell_types


write.csv(ucell_results, file = file.path(output_folder,"getSign_results.csv"))
 
 
```

